
CREATE TABLE EMPLOYEE (
    EMPLOYEE_NO   CHAR(8)         NOT NULL,
    EMPLOYEE_PASS   VARCHAR(10)    NOT NULL,
    EMPLOYEE_TRY_NO   VARCHAR(2)    NOT NULL, /*嘗試次數*/
    EMPLOYEE_PUR   VARCHAR(2)    NOT NULL, /*權限*/
    CONSTRAINT PK PRIMARY KEY(EMPLOYEE_NO)
);

/*試驗登入 */
insert into employee(EMPLOYEE_NO,EMPLOYEE_PASS,EMPLOYEE_TRY_NO,EMPLOYEE_PUR) values('admin','admin','0','1');

COMMIT;

