/*員工資訊*/
CREATE TABLE ACCOUNT (
    ACCOUNT_NO   CHAR(8)         NOT NULL, /*員工編號*/
    ACCOUNT_PASS   VARCHAR(200)    NOT NULL, /*密碼*/
    ACCOUNT_LOGIN_TIME   timestamp, /*最新登入時間*/
    ACCOUNT_TRY_NO   VARCHAR(2)    NOT NULL, /*嘗試次數*/
    ACCOUNT_PUR   VARCHAR(2)    NOT NULL, /*權限*/
    CONSTRAINT PK_ACCOUNT PRIMARY KEY(EMPLOYEE_NO)
);

/*交通費*/
CREATE TABLE TRANSPORT_COST (
TRANSPORT_NO   CHAR(8)         NOT NULL,/*員工編號*/
TRANSPORT_FARE   VARCHAR(10)    NOT NULL,/*交通費*/
TRANSPORT_UPLOAD_DATE   DATE    NOT NULL, /*上傳日期 YYYY/MM/DD */
TRANSPORT_UPDATE_DATE   DATE    NOT NULL, /*更新日期 YYYY/MM/DD */
TRANSPORT_DEADLINE   DATE    NOT NULL, /*嘗試期限 YYYY/MM/DD*/
TRANSPORT_PUR   VARCHAR(2)    NOT NULL, /*0:審核中 1:審核通過 2:審核不可*/
  CONSTRAINT PK_TRANSPORT_COST PRIMARY KEY (CustomerID, CustomerName)
);

/*資訊推播*/
CREATE TABLE MESSAGE(
  MESSAGE_NO VARCHAR (8) NOT NULL ,  /*員工號碼*/
  MESSAGE_CONTENT VARCHAR (100) NOT NULL ,  /*訊息內容*/
  MESSAGE_SEND_FLG VARCHAR (1) NOT NULL,  /*1:配信完 0:未配信 */
  MESSAGE_LEVEL VARCHAR (1) NOT NULL ,  /*0-4 level 0:一般推播 公司活動資訊等  1:月次訊息 繳交交通費與時數表 2:重要訊息 申請到期/時限將至等  3:未定 4:未定*/
  MESSAGE_CREATE_TIME timestamp NOT NULL ,  /*訊息創建時間*/
  MESSAGE_SEND_TIME timestamp ,  /*配信時間*/
  MESSAGE_CREATE_NO VARCHAR (8) NOT NULL ,  /*創建訊息者*/
  CONSTRAINT PK_MESSAGE PRIMARY KEY (MESSAGE_NO, MESSAGE_CONTENT)
);

